import type { SectorConfig } from "./types";

export const agriculturalConfig: SectorConfig = {
  sector: "AGRICULTURAL",
  nameAr: "زراعي",
  nameEn: "Agricultural",
  chartOfAccounts: [
    {
      code: "1",
      nameAr: "الأصول",
      nameEn: "Assets",
      type: "ASSET",
      nature: "DEBIT",
      isSystem: true,
      children: [
        {
          code: "11",
          nameAr: "الأصول المتداولة",
          nameEn: "Current Assets",
          type: "ASSET",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "1101", nameAr: "الصندوق", nameEn: "Cash on Hand", type: "ASSET", nature: "DEBIT", isSystem: true, sectorTag: "cash" },
            { code: "1102", nameAr: "البنك", nameEn: "Bank", type: "ASSET", nature: "DEBIT", isSystem: true, sectorTag: "bank" },
            { code: "1103", nameAr: "العملاء (المدينون)", nameEn: "Accounts Receivable", type: "ASSET", nature: "DEBIT", sectorTag: "ar" },
            { code: "1104", nameAr: "الأصول البيولوجية - ماشية", nameEn: "Biological Assets - Livestock", type: "ASSET", nature: "DEBIT", sectorTag: "livestock" },
            { code: "1105", nameAr: "الأصول البيولوجية - محاصيل", nameEn: "Biological Assets - Crops", type: "ASSET", nature: "DEBIT", sectorTag: "crops" },
            { code: "1106", nameAr: "المخزون الزراعي", nameEn: "Agricultural Inventory", type: "ASSET", nature: "DEBIT", sectorTag: "agri_inventory" },
          ],
        },
        {
          code: "12",
          nameAr: "الأصول غير المتداولة",
          nameEn: "Non-Current Assets",
          type: "ASSET",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "1201", nameAr: "الأراضي الزراعية", nameEn: "Agricultural Land", type: "ASSET", nature: "DEBIT", sectorTag: "land" },
            { code: "1202", nameAr: "المعدات الزراعية", nameEn: "Agricultural Equipment", type: "ASSET", nature: "DEBIT", sectorTag: "ppe" },
            { code: "1203", nameAr: "مجمع الإهلاك", nameEn: "Accumulated Depreciation", type: "ASSET", nature: "CREDIT", sectorTag: "acc_dep" },
          ],
        },
      ],
    },
    {
      code: "2",
      nameAr: "الخصوم (الالتزامات)",
      nameEn: "Liabilities",
      type: "LIABILITY",
      nature: "CREDIT",
      isSystem: true,
      children: [
        {
          code: "21",
          nameAr: "الخصوم المتداولة",
          nameEn: "Current Liabilities",
          type: "LIABILITY",
          nature: "CREDIT",
          isSystem: true,
          children: [
            { code: "2101", nameAr: "الموردون (الدائنون)", nameEn: "Accounts Payable", type: "LIABILITY", nature: "CREDIT", sectorTag: "ap" },
            { code: "2102", nameAr: "قروض زراعية", nameEn: "Agricultural Loans", type: "LIABILITY", nature: "CREDIT", sectorTag: "agri_loans" },
            { code: "2103", nameAr: "دعم حكومي مؤجل", nameEn: "Government Subsidies Deferred", type: "LIABILITY", nature: "CREDIT", sectorTag: "subsidies_deferred" },
          ],
        },
      ],
    },
    {
      code: "3",
      nameAr: "حقوق الملكية",
      nameEn: "Equity",
      type: "EQUITY",
      nature: "CREDIT",
      isSystem: true,
      children: [
        { code: "3101", nameAr: "رأس المال", nameEn: "Capital", type: "EQUITY", nature: "CREDIT", isSystem: true, sectorTag: "capital" },
        { code: "3102", nameAr: "أرباح مبقاة", nameEn: "Retained Earnings", type: "EQUITY", nature: "CREDIT", isSystem: true, sectorTag: "retained_earnings" },
        { code: "3103", nameAr: "احتياطي إعادة تقييم الأصول البيولوجية", nameEn: "Biological Asset Revaluation Reserve", type: "EQUITY", nature: "CREDIT", sectorTag: "bio_revaluation_reserve" },
      ],
    },
    {
      code: "4",
      nameAr: "الإيرادات",
      nameEn: "Revenue",
      type: "REVENUE",
      nature: "CREDIT",
      isSystem: true,
      children: [
        { code: "4101", nameAr: "مبيعات المحاصيل", nameEn: "Crop Sales", type: "REVENUE", nature: "CREDIT", isSystem: true, sectorTag: "crop_sales" },
        { code: "4102", nameAr: "مبيعات الماشية", nameEn: "Livestock Sales", type: "REVENUE", nature: "CREDIT", sectorTag: "livestock_sales" },
        { code: "4201", nameAr: "الدعم الحكومي", nameEn: "Government Subsidies", type: "REVENUE", nature: "CREDIT", sectorTag: "subsidies_income" },
      ],
    },
    {
      code: "5",
      nameAr: "المصروفات",
      nameEn: "Expenses",
      type: "EXPENSE",
      nature: "DEBIT",
      isSystem: true,
      children: [
        {
          code: "51",
          nameAr: "تكاليف الإنتاج الزراعي",
          nameEn: "Agricultural Production Costs",
          type: "EXPENSE",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "5101", nameAr: "بذور وأسمدة", nameEn: "Seeds & Fertilizers", type: "EXPENSE", nature: "DEBIT", sectorTag: "seeds_fertilizers" },
            { code: "5102", nameAr: "أعلاف حيوانية", nameEn: "Animal Feed", type: "EXPENSE", nature: "DEBIT", sectorTag: "animal_feed" },
            { code: "5103", nameAr: "عمالة موسمية", nameEn: "Seasonal Labor", type: "EXPENSE", nature: "DEBIT", sectorTag: "seasonal_labor" },
            { code: "5104", nameAr: "مصاريف الري", nameEn: "Irrigation Expenses", type: "EXPENSE", nature: "DEBIT", sectorTag: "irrigation" },
            { code: "5105", nameAr: "صيانة المعدات", nameEn: "Equipment Maintenance", type: "EXPENSE", nature: "DEBIT", sectorTag: "equipment_maintenance" },
          ],
        },
        {
          code: "52",
          nameAr: "المصروفات التشغيلية",
          nameEn: "Operating Expenses",
          type: "EXPENSE",
          nature: "DEBIT",
          children: [
            { code: "5201", nameAr: "الرواتب والأجور", nameEn: "Salaries & Wages", type: "EXPENSE", nature: "DEBIT", sectorTag: "salaries" },
            { code: "5202", nameAr: "الكهرباء والمياه", nameEn: "Utilities", type: "EXPENSE", nature: "DEBIT", sectorTag: "utilities" },
            { code: "5203", nameAr: "مصاريف الإهلاك", nameEn: "Depreciation Expense", type: "EXPENSE", nature: "DEBIT", sectorTag: "depreciation" },
            { code: "5204", nameAr: "مصاريف متنوعة", nameEn: "Miscellaneous Expenses", type: "EXPENSE", nature: "DEBIT" },
          ],
        },
      ],
    },
  ],
  financialStatementMapping: {
    incomeStatement: [
      { key: "agricultural_sales", nameAr: "المبيعات الزراعية", nameEn: "Agricultural Sales", sectorTags: ["crop_sales", "livestock_sales"] },
      { key: "subsidies", nameAr: "الدعم الحكومي", nameEn: "Government Subsidies", sectorTags: ["subsidies_income"] },
      { key: "production_costs", nameAr: "تكاليف الإنتاج الزراعي", nameEn: "Agricultural Production Costs", accountCodes: ["51"] },
      { key: "operating_expenses", nameAr: "المصروفات التشغيلية", nameEn: "Operating Expenses", accountCodes: ["52"] },
    ],
    balanceSheet: [
      { key: "current_assets", nameAr: "الأصول المتداولة", nameEn: "Current Assets", accountCodes: ["11"] },
      { key: "non_current_assets", nameAr: "الأصول غير المتداولة", nameEn: "Non-Current Assets", accountCodes: ["12"] },
      { key: "current_liabilities", nameAr: "الخصوم المتداولة", nameEn: "Current Liabilities", accountCodes: ["21"] },
      { key: "equity", nameAr: "حقوق الملكية", nameEn: "Equity", accountCodes: ["3"] },
    ],
  },
};
