import type { SectorConfig } from "./types";

export const bankingConfig: SectorConfig = {
  sector: "BANKING",
  nameAr: "مصرفي",
  nameEn: "Banking & Finance",
  chartOfAccounts: [
    {
      code: "1",
      nameAr: "الأصول",
      nameEn: "Assets",
      type: "ASSET",
      nature: "DEBIT",
      isSystem: true,
      children: [
        {
          code: "11",
          nameAr: "الأصول المتداولة",
          nameEn: "Current Assets",
          type: "ASSET",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "1101", nameAr: "الصندوق والنقد", nameEn: "Cash & Cash Equivalents", type: "ASSET", nature: "DEBIT", isSystem: true, sectorTag: "cash" },
            { code: "1102", nameAr: "أرصدة لدى البنك المركزي", nameEn: "Central Bank Deposits", type: "ASSET", nature: "DEBIT", sectorTag: "central_bank_deposits" },
            { code: "1103", nameAr: "أرصدة لدى البنوك", nameEn: "Interbank Deposits", type: "ASSET", nature: "DEBIT", sectorTag: "interbank_deposits" },
          ],
        },
        {
          code: "12",
          nameAr: "محفظة القروض",
          nameEn: "Loan Portfolio",
          type: "ASSET",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "1201", nameAr: "قروض شخصية", nameEn: "Personal Loans", type: "ASSET", nature: "DEBIT", sectorTag: "personal_loans" },
            { code: "1202", nameAr: "قروض تجارية", nameEn: "Commercial Loans", type: "ASSET", nature: "DEBIT", sectorTag: "commercial_loans" },
            { code: "1203", nameAr: "قروض عقارية", nameEn: "Mortgage Loans", type: "ASSET", nature: "DEBIT", sectorTag: "mortgage_loans" },
            { code: "1204", nameAr: "مخصص خسائر القروض", nameEn: "Provision for Loan Losses", type: "ASSET", nature: "CREDIT", sectorTag: "loan_provisions" },
          ],
        },
        {
          code: "13",
          nameAr: "الاستثمارات والأصول الثابتة",
          nameEn: "Investments & Fixed Assets",
          type: "ASSET",
          nature: "DEBIT",
          children: [
            { code: "1301", nameAr: "استثمارات مالية", nameEn: "Financial Investments", type: "ASSET", nature: "DEBIT", sectorTag: "investments" },
            { code: "1302", nameAr: "الأصول الثابتة", nameEn: "Fixed Assets", type: "ASSET", nature: "DEBIT", sectorTag: "ppe" },
            { code: "1303", nameAr: "مجمع الإهلاك", nameEn: "Accumulated Depreciation", type: "ASSET", nature: "CREDIT", sectorTag: "acc_dep" },
          ],
        },
      ],
    },
    {
      code: "2",
      nameAr: "الخصوم (الالتزامات)",
      nameEn: "Liabilities",
      type: "LIABILITY",
      nature: "CREDIT",
      isSystem: true,
      children: [
        {
          code: "21",
          nameAr: "ودائع العملاء",
          nameEn: "Customer Deposits",
          type: "LIABILITY",
          nature: "CREDIT",
          isSystem: true,
          children: [
            { code: "2101", nameAr: "حسابات جارية", nameEn: "Current Accounts", type: "LIABILITY", nature: "CREDIT", sectorTag: "current_accounts" },
            { code: "2102", nameAr: "حسابات توفير", nameEn: "Savings Accounts", type: "LIABILITY", nature: "CREDIT", sectorTag: "savings_accounts" },
            { code: "2103", nameAr: "ودائع لأجل", nameEn: "Term Deposits", type: "LIABILITY", nature: "CREDIT", sectorTag: "term_deposits" },
          ],
        },
        {
          code: "22",
          nameAr: "التزامات أخرى",
          nameEn: "Other Liabilities",
          type: "LIABILITY",
          nature: "CREDIT",
          children: [
            { code: "2201", nameAr: "اقتراض بين البنوك", nameEn: "Interbank Borrowings", type: "LIABILITY", nature: "CREDIT", sectorTag: "interbank_borrowings" },
            { code: "2202", nameAr: "سندات مصدرة", nameEn: "Bonds Issued", type: "LIABILITY", nature: "CREDIT", sectorTag: "bonds_issued" },
          ],
        },
      ],
    },
    {
      code: "3",
      nameAr: "حقوق الملكية",
      nameEn: "Equity",
      type: "EQUITY",
      nature: "CREDIT",
      isSystem: true,
      children: [
        { code: "3101", nameAr: "رأس المال", nameEn: "Capital", type: "EQUITY", nature: "CREDIT", isSystem: true, sectorTag: "capital" },
        { code: "3102", nameAr: "احتياطي قانوني", nameEn: "Statutory Reserve", type: "EQUITY", nature: "CREDIT", sectorTag: "statutory_reserve" },
        { code: "3103", nameAr: "احتياطي عام", nameEn: "General Reserve", type: "EQUITY", nature: "CREDIT", sectorTag: "general_reserve" },
        { code: "3104", nameAr: "أرباح مبقاة", nameEn: "Retained Earnings", type: "EQUITY", nature: "CREDIT", isSystem: true, sectorTag: "retained_earnings" },
      ],
    },
    {
      code: "4",
      nameAr: "الإيرادات",
      nameEn: "Revenue",
      type: "REVENUE",
      nature: "CREDIT",
      isSystem: true,
      children: [
        { code: "4101", nameAr: "إيرادات الفوائد - قروض", nameEn: "Interest Income - Loans", type: "REVENUE", nature: "CREDIT", isSystem: true, sectorTag: "interest_income_loans" },
        { code: "4102", nameAr: "إيرادات الفوائد - استثمارات", nameEn: "Interest Income - Investments", type: "REVENUE", nature: "CREDIT", sectorTag: "interest_income_investments" },
        { code: "4103", nameAr: "إيرادات الرسوم", nameEn: "Fee Income", type: "REVENUE", nature: "CREDIT", sectorTag: "fee_income" },
        { code: "4104", nameAr: "إيرادات العمولات", nameEn: "Commission Income", type: "REVENUE", nature: "CREDIT", sectorTag: "commission_income" },
      ],
    },
    {
      code: "5",
      nameAr: "المصروفات",
      nameEn: "Expenses",
      type: "EXPENSE",
      nature: "DEBIT",
      isSystem: true,
      children: [
        {
          code: "51",
          nameAr: "مصاريف الفوائد",
          nameEn: "Interest Expenses",
          type: "EXPENSE",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "5101", nameAr: "فوائد الودائع", nameEn: "Interest Expense - Deposits", type: "EXPENSE", nature: "DEBIT", sectorTag: "interest_expense_deposits" },
            { code: "5102", nameAr: "مصاريف المخصصات", nameEn: "Provision Expense", type: "EXPENSE", nature: "DEBIT", sectorTag: "provision_expense" },
          ],
        },
        {
          code: "52",
          nameAr: "المصروفات التشغيلية",
          nameEn: "Operating Expenses",
          type: "EXPENSE",
          nature: "DEBIT",
          children: [
            { code: "5201", nameAr: "الرواتب والأجور", nameEn: "Salaries & Wages", type: "EXPENSE", nature: "DEBIT", sectorTag: "salaries" },
            { code: "5202", nameAr: "الإيجار", nameEn: "Rent", type: "EXPENSE", nature: "DEBIT", sectorTag: "rent" },
            { code: "5203", nameAr: "الكهرباء والمياه", nameEn: "Utilities", type: "EXPENSE", nature: "DEBIT", sectorTag: "utilities" },
            { code: "5204", nameAr: "مصاريف الإهلاك", nameEn: "Depreciation Expense", type: "EXPENSE", nature: "DEBIT", sectorTag: "depreciation" },
            { code: "5205", nameAr: "مصاريف التقنية", nameEn: "Technology Expenses", type: "EXPENSE", nature: "DEBIT" },
            { code: "5206", nameAr: "مصاريف متنوعة", nameEn: "Miscellaneous Expenses", type: "EXPENSE", nature: "DEBIT" },
          ],
        },
      ],
    },
  ],
  financialStatementMapping: {
    incomeStatement: [
      { key: "interest_income", nameAr: "إيرادات الفوائد", nameEn: "Interest Income", sectorTags: ["interest_income_loans", "interest_income_investments"] },
      { key: "fee_commission_income", nameAr: "إيرادات الرسوم والعمولات", nameEn: "Fee & Commission Income", sectorTags: ["fee_income", "commission_income"] },
      { key: "interest_expenses", nameAr: "مصاريف الفوائد", nameEn: "Interest Expenses", accountCodes: ["51"] },
      { key: "operating_expenses", nameAr: "المصروفات التشغيلية", nameEn: "Operating Expenses", accountCodes: ["52"] },
    ],
    balanceSheet: [
      { key: "current_assets", nameAr: "الأصول المتداولة", nameEn: "Current Assets", accountCodes: ["11"] },
      { key: "loan_portfolio", nameAr: "محفظة القروض", nameEn: "Loan Portfolio", accountCodes: ["12"] },
      { key: "investments_fixed", nameAr: "الاستثمارات والأصول الثابتة", nameEn: "Investments & Fixed Assets", accountCodes: ["13"] },
      { key: "customer_deposits", nameAr: "ودائع العملاء", nameEn: "Customer Deposits", accountCodes: ["21"] },
      { key: "other_liabilities", nameAr: "التزامات أخرى", nameEn: "Other Liabilities", accountCodes: ["22"] },
      { key: "equity", nameAr: "حقوق الملكية", nameEn: "Equity", accountCodes: ["3"] },
    ],
  },
};
