import type { SectorConfig } from "./types";

export const commercialConfig: SectorConfig = {
  sector: "COMMERCIAL",
  nameAr: "تجاري",
  nameEn: "Commercial (Trading)",
  chartOfAccounts: [
    {
      code: "1",
      nameAr: "الأصول",
      nameEn: "Assets",
      type: "ASSET",
      nature: "DEBIT",
      isSystem: true,
      children: [
        {
          code: "11",
          nameAr: "الأصول المتداولة",
          nameEn: "Current Assets",
          type: "ASSET",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "1101", nameAr: "الصندوق", nameEn: "Cash on Hand", type: "ASSET", nature: "DEBIT", isSystem: true, sectorTag: "cash" },
            { code: "1102", nameAr: "البنك", nameEn: "Bank", type: "ASSET", nature: "DEBIT", isSystem: true, sectorTag: "bank" },
            { code: "1103", nameAr: "العملاء (المدينون)", nameEn: "Accounts Receivable", type: "ASSET", nature: "DEBIT", sectorTag: "ar" },
            { code: "1104", nameAr: "أوراق القبض", nameEn: "Notes Receivable", type: "ASSET", nature: "DEBIT", sectorTag: "notes_receivable" },
            { code: "1105", nameAr: "المخزون - بضاعة", nameEn: "Inventory - Merchandise", type: "ASSET", nature: "DEBIT", sectorTag: "inventory" },
            { code: "1106", nameAr: "مصروفات مدفوعة مقدمًا", nameEn: "Prepaid Expenses", type: "ASSET", nature: "DEBIT", sectorTag: "prepaid" },
            { code: "1107", nameAr: "ضريبة القيمة المضافة - مدينة", nameEn: "VAT Receivable", type: "ASSET", nature: "DEBIT", sectorTag: "vat_input" },
          ],
        },
        {
          code: "12",
          nameAr: "الأصول غير المتداولة",
          nameEn: "Non-Current Assets",
          type: "ASSET",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "1201", nameAr: "الأثاث والتجهيزات", nameEn: "Furniture & Fixtures", type: "ASSET", nature: "DEBIT", sectorTag: "ppe" },
            { code: "1202", nameAr: "المعدات", nameEn: "Equipment", type: "ASSET", nature: "DEBIT", sectorTag: "ppe" },
            { code: "1203", nameAr: "السيارات", nameEn: "Vehicles", type: "ASSET", nature: "DEBIT", sectorTag: "ppe" },
            { code: "1204", nameAr: "مجمع الإهلاك", nameEn: "Accumulated Depreciation", type: "ASSET", nature: "CREDIT", sectorTag: "acc_dep" },
          ],
        },
      ],
    },
    {
      code: "2",
      nameAr: "الخصوم (الالتزامات)",
      nameEn: "Liabilities",
      type: "LIABILITY",
      nature: "CREDIT",
      isSystem: true,
      children: [
        {
          code: "21",
          nameAr: "الخصوم المتداولة",
          nameEn: "Current Liabilities",
          type: "LIABILITY",
          nature: "CREDIT",
          isSystem: true,
          children: [
            { code: "2101", nameAr: "الموردون (الدائنون)", nameEn: "Accounts Payable", type: "LIABILITY", nature: "CREDIT", sectorTag: "ap" },
            { code: "2102", nameAr: "أوراق الدفع", nameEn: "Notes Payable", type: "LIABILITY", nature: "CREDIT", sectorTag: "notes_payable" },
            { code: "2103", nameAr: "مصروفات مستحقة", nameEn: "Accrued Expenses", type: "LIABILITY", nature: "CREDIT", sectorTag: "accrued" },
            { code: "2104", nameAr: "ضريبة القيمة المضافة - دائنة", nameEn: "VAT Payable", type: "LIABILITY", nature: "CREDIT", sectorTag: "vat_output" },
            { code: "2105", nameAr: "رواتب مستحقة", nameEn: "Salaries Payable", type: "LIABILITY", nature: "CREDIT", sectorTag: "salaries_payable" },
          ],
        },
        {
          code: "22",
          nameAr: "الخصوم طويلة الأجل",
          nameEn: "Long-Term Liabilities",
          type: "LIABILITY",
          nature: "CREDIT",
          children: [
            { code: "2201", nameAr: "قروض طويلة الأجل", nameEn: "Long-Term Loans", type: "LIABILITY", nature: "CREDIT", sectorTag: "lt_loans" },
          ],
        },
      ],
    },
    {
      code: "3",
      nameAr: "حقوق الملكية",
      nameEn: "Equity",
      type: "EQUITY",
      nature: "CREDIT",
      isSystem: true,
      children: [
        { code: "3101", nameAr: "رأس المال", nameEn: "Capital", type: "EQUITY", nature: "CREDIT", isSystem: true, sectorTag: "capital" },
        { code: "3102", nameAr: "أرباح مبقاة", nameEn: "Retained Earnings", type: "EQUITY", nature: "CREDIT", isSystem: true, sectorTag: "retained_earnings" },
        { code: "3103", nameAr: "المسحوبات الشخصية", nameEn: "Drawings", type: "EQUITY", nature: "DEBIT", sectorTag: "drawings" },
        { code: "3104", nameAr: "الاحتياطيات", nameEn: "Reserves", type: "EQUITY", nature: "CREDIT", sectorTag: "reserves" },
      ],
    },
    {
      code: "4",
      nameAr: "الإيرادات",
      nameEn: "Revenue",
      type: "REVENUE",
      nature: "CREDIT",
      isSystem: true,
      children: [
        { code: "4101", nameAr: "المبيعات", nameEn: "Sales Revenue", type: "REVENUE", nature: "CREDIT", isSystem: true, sectorTag: "sales" },
        { code: "4102", nameAr: "مردودات المبيعات", nameEn: "Sales Returns", type: "REVENUE", nature: "DEBIT", sectorTag: "sales_returns" },
        { code: "4103", nameAr: "خصم مسموح به", nameEn: "Sales Discount", type: "REVENUE", nature: "DEBIT", sectorTag: "sales_discount" },
        { code: "4201", nameAr: "إيرادات أخرى", nameEn: "Other Revenue", type: "REVENUE", nature: "CREDIT", sectorTag: "other_revenue" },
      ],
    },
    {
      code: "5",
      nameAr: "المصروفات",
      nameEn: "Expenses",
      type: "EXPENSE",
      nature: "DEBIT",
      isSystem: true,
      children: [
        {
          code: "51",
          nameAr: "تكلفة البضاعة المباعة",
          nameEn: "Cost of Goods Sold",
          type: "EXPENSE",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "5101", nameAr: "المشتريات", nameEn: "Purchases", type: "EXPENSE", nature: "DEBIT", isSystem: true, sectorTag: "purchases" },
            { code: "5102", nameAr: "مردودات المشتريات", nameEn: "Purchase Returns", type: "EXPENSE", nature: "CREDIT", sectorTag: "purchase_returns" },
            { code: "5103", nameAr: "خصم مكتسب", nameEn: "Purchase Discount", type: "EXPENSE", nature: "CREDIT", sectorTag: "purchase_discount" },
            { code: "5104", nameAr: "مصاريف نقل المشتريات", nameEn: "Freight In", type: "EXPENSE", nature: "DEBIT", sectorTag: "freight_in" },
          ],
        },
        {
          code: "52",
          nameAr: "المصروفات التشغيلية",
          nameEn: "Operating Expenses",
          type: "EXPENSE",
          nature: "DEBIT",
          children: [
            { code: "5201", nameAr: "الرواتب والأجور", nameEn: "Salaries & Wages", type: "EXPENSE", nature: "DEBIT", sectorTag: "salaries" },
            { code: "5202", nameAr: "الإيجار", nameEn: "Rent", type: "EXPENSE", nature: "DEBIT", sectorTag: "rent" },
            { code: "5203", nameAr: "الكهرباء والمياه", nameEn: "Utilities", type: "EXPENSE", nature: "DEBIT", sectorTag: "utilities" },
            { code: "5204", nameAr: "الاتصالات", nameEn: "Telecommunications", type: "EXPENSE", nature: "DEBIT" },
            { code: "5205", nameAr: "مصاريف الصيانة", nameEn: "Maintenance", type: "EXPENSE", nature: "DEBIT" },
            { code: "5206", nameAr: "مصاريف التسويق والإعلان", nameEn: "Marketing & Advertising", type: "EXPENSE", nature: "DEBIT" },
            { code: "5207", nameAr: "مصاريف الإهلاك", nameEn: "Depreciation Expense", type: "EXPENSE", nature: "DEBIT", sectorTag: "depreciation" },
            { code: "5208", nameAr: "مصاريف التأمين", nameEn: "Insurance Expense", type: "EXPENSE", nature: "DEBIT" },
            { code: "5209", nameAr: "مصاريف بنكية", nameEn: "Bank Charges", type: "EXPENSE", nature: "DEBIT" },
            { code: "5210", nameAr: "مصاريف متنوعة", nameEn: "Miscellaneous Expenses", type: "EXPENSE", nature: "DEBIT" },
          ],
        },
      ],
    },
  ],
  financialStatementMapping: {
    incomeStatement: [
      { key: "sales", nameAr: "المبيعات", nameEn: "Sales", sectorTags: ["sales"] },
      { key: "sales_returns", nameAr: "مردودات المبيعات", nameEn: "Sales Returns", sectorTags: ["sales_returns", "sales_discount"] },
      { key: "cogs", nameAr: "تكلفة البضاعة المباعة", nameEn: "Cost of Goods Sold", sectorTags: ["purchases", "purchase_returns", "purchase_discount", "freight_in"] },
      { key: "operating_expenses", nameAr: "المصروفات التشغيلية", nameEn: "Operating Expenses", accountCodes: ["52"] },
      { key: "other_revenue", nameAr: "إيرادات أخرى", nameEn: "Other Revenue", sectorTags: ["other_revenue"] },
    ],
    balanceSheet: [
      { key: "current_assets", nameAr: "الأصول المتداولة", nameEn: "Current Assets", accountCodes: ["11"] },
      { key: "non_current_assets", nameAr: "الأصول غير المتداولة", nameEn: "Non-Current Assets", accountCodes: ["12"] },
      { key: "current_liabilities", nameAr: "الخصوم المتداولة", nameEn: "Current Liabilities", accountCodes: ["21"] },
      { key: "non_current_liabilities", nameAr: "الخصوم طويلة الأجل", nameEn: "Long-Term Liabilities", accountCodes: ["22"] },
      { key: "equity", nameAr: "حقوق الملكية", nameEn: "Equity", accountCodes: ["3"] },
    ],
  },
};
