import type { SectorConfig } from "./types";

export const contractingConfig: SectorConfig = {
  sector: "CONTRACTING",
  nameAr: "مقاولات",
  nameEn: "Contracting",
  chartOfAccounts: [
    {
      code: "1",
      nameAr: "الأصول",
      nameEn: "Assets",
      type: "ASSET",
      nature: "DEBIT",
      isSystem: true,
      children: [
        {
          code: "11",
          nameAr: "الأصول المتداولة",
          nameEn: "Current Assets",
          type: "ASSET",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "1101", nameAr: "الصندوق", nameEn: "Cash on Hand", type: "ASSET", nature: "DEBIT", isSystem: true, sectorTag: "cash" },
            { code: "1102", nameAr: "البنك", nameEn: "Bank", type: "ASSET", nature: "DEBIT", isSystem: true, sectorTag: "bank" },
            { code: "1103", nameAr: "العملاء (المدينون)", nameEn: "Accounts Receivable", type: "ASSET", nature: "DEBIT", sectorTag: "ar" },
            { code: "1104", nameAr: "محتجزات لدى العملاء", nameEn: "Retentions Receivable", type: "ASSET", nature: "DEBIT", sectorTag: "retentions_receivable" },
            { code: "1105", nameAr: "إيرادات غير مفوترة", nameEn: "Unbilled Revenue", type: "ASSET", nature: "DEBIT", sectorTag: "unbilled_revenue" },
            { code: "1106", nameAr: "مخزون المواد", nameEn: "Materials Inventory", type: "ASSET", nature: "DEBIT", sectorTag: "materials_inventory" },
          ],
        },
        {
          code: "12",
          nameAr: "الأصول غير المتداولة",
          nameEn: "Non-Current Assets",
          type: "ASSET",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "1201", nameAr: "المعدات الثقيلة", nameEn: "Heavy Equipment", type: "ASSET", nature: "DEBIT", sectorTag: "ppe" },
            { code: "1202", nameAr: "السيارات", nameEn: "Vehicles", type: "ASSET", nature: "DEBIT", sectorTag: "ppe" },
            { code: "1203", nameAr: "مجمع الإهلاك", nameEn: "Accumulated Depreciation", type: "ASSET", nature: "CREDIT", sectorTag: "acc_dep" },
          ],
        },
      ],
    },
    {
      code: "2",
      nameAr: "الخصوم (الالتزامات)",
      nameEn: "Liabilities",
      type: "LIABILITY",
      nature: "CREDIT",
      isSystem: true,
      children: [
        {
          code: "21",
          nameAr: "الخصوم المتداولة",
          nameEn: "Current Liabilities",
          type: "LIABILITY",
          nature: "CREDIT",
          isSystem: true,
          children: [
            { code: "2101", nameAr: "الموردون (الدائنون)", nameEn: "Accounts Payable", type: "LIABILITY", nature: "CREDIT", sectorTag: "ap" },
            { code: "2102", nameAr: "مستحقات مقاولي الباطن", nameEn: "Subcontractor Payable", type: "LIABILITY", nature: "CREDIT", sectorTag: "subcontractor_payable" },
            { code: "2103", nameAr: "محتجزات مستحقة", nameEn: "Retentions Payable", type: "LIABILITY", nature: "CREDIT", sectorTag: "retentions_payable" },
            { code: "2104", nameAr: "دفعات مقدمة من العملاء", nameEn: "Advance Payments from Clients", type: "LIABILITY", nature: "CREDIT", sectorTag: "advance_payments" },
            { code: "2105", nameAr: "مخصصات", nameEn: "Provisions", type: "LIABILITY", nature: "CREDIT", sectorTag: "provisions" },
          ],
        },
      ],
    },
    {
      code: "3",
      nameAr: "حقوق الملكية",
      nameEn: "Equity",
      type: "EQUITY",
      nature: "CREDIT",
      isSystem: true,
      children: [
        { code: "3101", nameAr: "رأس المال", nameEn: "Capital", type: "EQUITY", nature: "CREDIT", isSystem: true, sectorTag: "capital" },
        { code: "3102", nameAr: "أرباح مبقاة", nameEn: "Retained Earnings", type: "EQUITY", nature: "CREDIT", isSystem: true, sectorTag: "retained_earnings" },
      ],
    },
    {
      code: "4",
      nameAr: "الإيرادات",
      nameEn: "Revenue",
      type: "REVENUE",
      nature: "CREDIT",
      isSystem: true,
      children: [
        { code: "4101", nameAr: "إيرادات العقود", nameEn: "Contract Revenue", type: "REVENUE", nature: "CREDIT", isSystem: true, sectorTag: "contract_revenue" },
        { code: "4102", nameAr: "إيرادات الأوامر التغييرية", nameEn: "Variation Orders Revenue", type: "REVENUE", nature: "CREDIT", sectorTag: "variation_orders" },
      ],
    },
    {
      code: "5",
      nameAr: "المصروفات",
      nameEn: "Expenses",
      type: "EXPENSE",
      nature: "DEBIT",
      isSystem: true,
      children: [
        {
          code: "51",
          nameAr: "تكاليف المشاريع المباشرة",
          nameEn: "Direct Project Costs",
          type: "EXPENSE",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "5101", nameAr: "مواد مباشرة", nameEn: "Direct Materials", type: "EXPENSE", nature: "DEBIT", sectorTag: "direct_materials" },
            { code: "5102", nameAr: "عمالة مباشرة", nameEn: "Direct Labor", type: "EXPENSE", nature: "DEBIT", sectorTag: "direct_labor" },
            { code: "5103", nameAr: "تكاليف مقاولي الباطن", nameEn: "Subcontractor Costs", type: "EXPENSE", nature: "DEBIT", sectorTag: "subcontractor_costs" },
            { code: "5104", nameAr: "تكاليف المعدات", nameEn: "Equipment Costs", type: "EXPENSE", nature: "DEBIT", sectorTag: "equipment_costs" },
            { code: "5105", nameAr: "مصاريف الموقع", nameEn: "Site Expenses", type: "EXPENSE", nature: "DEBIT", sectorTag: "site_expenses" },
          ],
        },
        {
          code: "52",
          nameAr: "المصروفات التشغيلية",
          nameEn: "Operating Expenses",
          type: "EXPENSE",
          nature: "DEBIT",
          children: [
            { code: "5201", nameAr: "الرواتب والأجور", nameEn: "Salaries & Wages", type: "EXPENSE", nature: "DEBIT", sectorTag: "salaries" },
            { code: "5202", nameAr: "الإيجار", nameEn: "Rent", type: "EXPENSE", nature: "DEBIT", sectorTag: "rent" },
            { code: "5203", nameAr: "الكهرباء والمياه", nameEn: "Utilities", type: "EXPENSE", nature: "DEBIT", sectorTag: "utilities" },
            { code: "5204", nameAr: "مصاريف الإهلاك", nameEn: "Depreciation Expense", type: "EXPENSE", nature: "DEBIT", sectorTag: "depreciation" },
            { code: "5205", nameAr: "مصاريف متنوعة", nameEn: "Miscellaneous Expenses", type: "EXPENSE", nature: "DEBIT" },
          ],
        },
      ],
    },
  ],
  financialStatementMapping: {
    incomeStatement: [
      { key: "contract_revenue", nameAr: "إيرادات العقود", nameEn: "Contract Revenue", sectorTags: ["contract_revenue", "variation_orders"] },
      { key: "direct_costs", nameAr: "تكاليف المشاريع المباشرة", nameEn: "Direct Project Costs", accountCodes: ["51"] },
      { key: "operating_expenses", nameAr: "المصروفات التشغيلية", nameEn: "Operating Expenses", accountCodes: ["52"] },
    ],
    balanceSheet: [
      { key: "current_assets", nameAr: "الأصول المتداولة", nameEn: "Current Assets", accountCodes: ["11"] },
      { key: "non_current_assets", nameAr: "الأصول غير المتداولة", nameEn: "Non-Current Assets", accountCodes: ["12"] },
      { key: "current_liabilities", nameAr: "الخصوم المتداولة", nameEn: "Current Liabilities", accountCodes: ["21"] },
      { key: "equity", nameAr: "حقوق الملكية", nameEn: "Equity", accountCodes: ["3"] },
    ],
  },
};
