import type { SectorConfig } from "./types";

export const industrialConfig: SectorConfig = {
  sector: "INDUSTRIAL",
  nameAr: "صناعي",
  nameEn: "Industrial (Manufacturing)",
  chartOfAccounts: [
    {
      code: "1",
      nameAr: "الأصول",
      nameEn: "Assets",
      type: "ASSET",
      nature: "DEBIT",
      isSystem: true,
      children: [
        {
          code: "11",
          nameAr: "الأصول المتداولة",
          nameEn: "Current Assets",
          type: "ASSET",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "1101", nameAr: "الصندوق", nameEn: "Cash on Hand", type: "ASSET", nature: "DEBIT", isSystem: true, sectorTag: "cash" },
            { code: "1102", nameAr: "البنك", nameEn: "Bank", type: "ASSET", nature: "DEBIT", isSystem: true, sectorTag: "bank" },
            { code: "1103", nameAr: "العملاء (المدينون)", nameEn: "Accounts Receivable", type: "ASSET", nature: "DEBIT", sectorTag: "ar" },
            { code: "1104", nameAr: "أوراق القبض", nameEn: "Notes Receivable", type: "ASSET", nature: "DEBIT", sectorTag: "notes_receivable" },
            // مخزون متعدد المراحل — دورة الإنتاج الكاملة
            { code: "1110", nameAr: "مخزون المواد الخام — غزل", nameEn: "Raw Materials — Yarn", type: "ASSET", nature: "DEBIT", sectorTag: "raw_yarn" },
            { code: "1111", nameAr: "مخزون المواد الخام — كيماويات وأصباغ", nameEn: "Raw Materials — Chemicals & Dyes", type: "ASSET", nature: "DEBIT", sectorTag: "raw_chemicals" },
            { code: "1112", nameAr: "مخزون المواد الخام — إكسسوارات (أزرار، سوست)", nameEn: "Raw Materials — Accessories", type: "ASSET", nature: "DEBIT", sectorTag: "raw_accessories" },
            { code: "1113", nameAr: "مخزون المواد الخام — مواد تغليف", nameEn: "Raw Materials — Packaging", type: "ASSET", nature: "DEBIT", sectorTag: "raw_packaging" },
            { code: "1120", nameAr: "إنتاج تحت التشغيل — نسيج (عند المقاول)", nameEn: "WIP — Weaving (Outsourced)", type: "ASSET", nature: "DEBIT", sectorTag: "wip_weaving" },
            { code: "1121", nameAr: "إنتاج تحت التشغيل — صباغة (عند المقاول)", nameEn: "WIP — Dyeing (Outsourced)", type: "ASSET", nature: "DEBIT", sectorTag: "wip_dyeing" },
            { code: "1122", nameAr: "إنتاج تحت التشغيل — قص", nameEn: "WIP — Cutting", type: "ASSET", nature: "DEBIT", sectorTag: "wip_cutting" },
            { code: "1123", nameAr: "إنتاج تحت التشغيل — خياطة", nameEn: "WIP — Sewing", type: "ASSET", nature: "DEBIT", sectorTag: "wip_sewing" },
            { code: "1124", nameAr: "إنتاج تحت التشغيل — تشطيب وكي", nameEn: "WIP — Finishing", type: "ASSET", nature: "DEBIT", sectorTag: "wip_finishing" },
            { code: "1130", nameAr: "مخزون البضاعة التامة (ملابس جاهزة)", nameEn: "Finished Goods — Garments", type: "ASSET", nature: "DEBIT", sectorTag: "finished_goods" },
            { code: "1131", nameAr: "مخزون قماش خام (بعد النسيج)", nameEn: "Fabric Inventory — Raw", type: "ASSET", nature: "DEBIT", sectorTag: "fabric_raw" },
            { code: "1132", nameAr: "مخزون قماش مصبوغ", nameEn: "Fabric Inventory — Dyed", type: "ASSET", nature: "DEBIT", sectorTag: "fabric_dyed" },
            { code: "1140", nameAr: "مصروفات مدفوعة مقدمًا", nameEn: "Prepaid Expenses", type: "ASSET", nature: "DEBIT", sectorTag: "prepaid" },
            { code: "1141", nameAr: "دفعات مقدمة لمقاولين", nameEn: "Advances to Subcontractors", type: "ASSET", nature: "DEBIT", sectorTag: "advances_subcontractors" },
            { code: "1150", nameAr: "ضريبة القيمة المضافة — مدينة", nameEn: "VAT Receivable", type: "ASSET", nature: "DEBIT", sectorTag: "vat_input" },
          ],
        },
        {
          code: "12",
          nameAr: "الأصول غير المتداولة",
          nameEn: "Non-Current Assets",
          type: "ASSET",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "1201", nameAr: "ماكينات الخياطة", nameEn: "Sewing Machines", type: "ASSET", nature: "DEBIT", sectorTag: "ppe_sewing" },
            { code: "1202", nameAr: "ماكينات القص", nameEn: "Cutting Machines", type: "ASSET", nature: "DEBIT", sectorTag: "ppe_cutting" },
            { code: "1203", nameAr: "ماكينات الكي والتشطيب", nameEn: "Finishing & Pressing Machines", type: "ASSET", nature: "DEBIT", sectorTag: "ppe_finishing" },
            { code: "1204", nameAr: "معدات التغليف", nameEn: "Packaging Equipment", type: "ASSET", nature: "DEBIT", sectorTag: "ppe_packaging" },
            { code: "1205", nameAr: "المباني والمصنع", nameEn: "Factory Buildings", type: "ASSET", nature: "DEBIT", sectorTag: "buildings" },
            { code: "1206", nameAr: "السيارات ووسائل النقل", nameEn: "Vehicles", type: "ASSET", nature: "DEBIT", sectorTag: "vehicles" },
            { code: "1207", nameAr: "أثاث وتجهيزات مكتبية", nameEn: "Office Furniture", type: "ASSET", nature: "DEBIT", sectorTag: "furniture" },
            { code: "1208", nameAr: "أجهزة كمبيوتر وبرمجيات", nameEn: "IT Equipment", type: "ASSET", nature: "DEBIT", sectorTag: "it" },
            { code: "1290", nameAr: "مجمع إهلاك الأصول الثابتة", nameEn: "Accumulated Depreciation", type: "ASSET", nature: "CREDIT", sectorTag: "acc_dep" },
          ],
        },
      ],
    },
    {
      code: "2",
      nameAr: "الخصوم (الالتزامات)",
      nameEn: "Liabilities",
      type: "LIABILITY",
      nature: "CREDIT",
      isSystem: true,
      children: [
        {
          code: "21",
          nameAr: "الخصوم المتداولة",
          nameEn: "Current Liabilities",
          type: "LIABILITY",
          nature: "CREDIT",
          isSystem: true,
          children: [
            { code: "2101", nameAr: "موردون — مواد خام (غزل)", nameEn: "AP — Yarn Suppliers", type: "LIABILITY", nature: "CREDIT", sectorTag: "ap_yarn" },
            { code: "2102", nameAr: "موردون — إكسسوارات ومستلزمات", nameEn: "AP — Accessories Suppliers", type: "LIABILITY", nature: "CREDIT", sectorTag: "ap_accessories" },
            { code: "2103", nameAr: "مقاولون — نسيج", nameEn: "AP — Weaving Contractors", type: "LIABILITY", nature: "CREDIT", sectorTag: "ap_weaving" },
            { code: "2104", nameAr: "مقاولون — صباغة", nameEn: "AP — Dyeing Contractors", type: "LIABILITY", nature: "CREDIT", sectorTag: "ap_dyeing" },
            { code: "2105", nameAr: "مصروفات مستحقة", nameEn: "Accrued Expenses", type: "LIABILITY", nature: "CREDIT", sectorTag: "accrued" },
            { code: "2106", nameAr: "رواتب وأجور مستحقة", nameEn: "Salaries Payable", type: "LIABILITY", nature: "CREDIT", sectorTag: "salaries_payable" },
            { code: "2107", nameAr: "تأمينات اجتماعية مستحقة", nameEn: "GOSI Payable", type: "LIABILITY", nature: "CREDIT", sectorTag: "gosi_payable" },
            { code: "2108", nameAr: "ضريبة القيمة المضافة — دائنة", nameEn: "VAT Payable", type: "LIABILITY", nature: "CREDIT", sectorTag: "vat_output" },
            { code: "2109", nameAr: "دفعات مقدمة من عملاء", nameEn: "Customer Advances", type: "LIABILITY", nature: "CREDIT", sectorTag: "customer_advances" },
          ],
        },
        {
          code: "22",
          nameAr: "الخصوم طويلة الأجل",
          nameEn: "Long-Term Liabilities",
          type: "LIABILITY",
          nature: "CREDIT",
          children: [
            { code: "2201", nameAr: "قروض طويلة الأجل", nameEn: "Long-Term Loans", type: "LIABILITY", nature: "CREDIT", sectorTag: "lt_loans" },
            { code: "2202", nameAr: "التزامات نهاية الخدمة", nameEn: "End of Service Liability", type: "LIABILITY", nature: "CREDIT", sectorTag: "eos_liability" },
          ],
        },
      ],
    },
    {
      code: "3",
      nameAr: "حقوق الملكية",
      nameEn: "Equity",
      type: "EQUITY",
      nature: "CREDIT",
      isSystem: true,
      children: [
        { code: "3101", nameAr: "رأس المال", nameEn: "Capital", type: "EQUITY", nature: "CREDIT", isSystem: true, sectorTag: "capital" },
        { code: "3102", nameAr: "أرباح مبقاة", nameEn: "Retained Earnings", type: "EQUITY", nature: "CREDIT", isSystem: true, sectorTag: "retained_earnings" },
        { code: "3103", nameAr: "المسحوبات الشخصية", nameEn: "Drawings", type: "EQUITY", nature: "DEBIT", sectorTag: "drawings" },
        { code: "3104", nameAr: "الاحتياطيات", nameEn: "Reserves", type: "EQUITY", nature: "CREDIT", sectorTag: "reserves" },
      ],
    },
    {
      code: "4",
      nameAr: "الإيرادات",
      nameEn: "Revenue",
      type: "REVENUE",
      nature: "CREDIT",
      isSystem: true,
      children: [
        { code: "4101", nameAr: "مبيعات جملة — ملابس جاهزة", nameEn: "Wholesale Sales — Garments", type: "REVENUE", nature: "CREDIT", isSystem: true, sectorTag: "sales_wholesale" },
        { code: "4102", nameAr: "مبيعات تجزئة — ملابس جاهزة", nameEn: "Retail Sales — Garments", type: "REVENUE", nature: "CREDIT", sectorTag: "sales_retail" },
        { code: "4103", nameAr: "مبيعات تصدير", nameEn: "Export Sales", type: "REVENUE", nature: "CREDIT", sectorTag: "sales_export" },
        { code: "4104", nameAr: "مبيعات أقمشة (خام/مصبوغ)", nameEn: "Fabric Sales", type: "REVENUE", nature: "CREDIT", sectorTag: "sales_fabric" },
        { code: "4120", nameAr: "مردودات المبيعات", nameEn: "Sales Returns", type: "REVENUE", nature: "DEBIT", sectorTag: "sales_returns" },
        { code: "4121", nameAr: "خصم مسموح به", nameEn: "Sales Discount", type: "REVENUE", nature: "DEBIT", sectorTag: "sales_discount" },
        { code: "4201", nameAr: "إيرادات أخرى", nameEn: "Other Revenue", type: "REVENUE", nature: "CREDIT", sectorTag: "other_revenue" },
        { code: "4202", nameAr: "إيرادات هوالك وبواقي (scraps)", nameEn: "Scrap Revenue", type: "REVENUE", nature: "CREDIT", sectorTag: "scrap_revenue" },
      ],
    },
    {
      code: "5",
      nameAr: "المصروفات",
      nameEn: "Expenses",
      type: "EXPENSE",
      nature: "DEBIT",
      isSystem: true,
      children: [
        {
          code: "51",
          nameAr: "تكلفة الإنتاج المباشرة",
          nameEn: "Direct Production Costs",
          type: "EXPENSE",
          nature: "DEBIT",
          isSystem: true,
          children: [
            // مرحلة 1: شراء الغزل
            { code: "5101", nameAr: "مواد خام — غزل مستخدم", nameEn: "Raw Materials — Yarn Used", type: "EXPENSE", nature: "DEBIT", sectorTag: "yarn_used" },
            { code: "5102", nameAr: "مواد خام — إكسسوارات ومستلزمات", nameEn: "Accessories & Supplies Used", type: "EXPENSE", nature: "DEBIT", sectorTag: "accessories_used" },
            // مرحلة 2: مقاولين نسيج
            { code: "5110", nameAr: "تكلفة مقاول النسيج", nameEn: "Weaving Contractor Cost", type: "EXPENSE", nature: "DEBIT", sectorTag: "weaving_cost" },
            { code: "5111", nameAr: "نقل مواد للنسيج (ذهاب وإياب)", nameEn: "Weaving Transport Cost", type: "EXPENSE", nature: "DEBIT", sectorTag: "weaving_transport" },
            // مرحلة 3: مقاولين صباغة
            { code: "5115", nameAr: "تكلفة مقاول الصباغة", nameEn: "Dyeing Contractor Cost", type: "EXPENSE", nature: "DEBIT", sectorTag: "dyeing_cost" },
            { code: "5116", nameAr: "كيماويات وأصباغ", nameEn: "Chemicals & Dyes Cost", type: "EXPENSE", nature: "DEBIT", sectorTag: "chemicals_cost" },
            { code: "5117", nameAr: "نقل مواد للصباغة", nameEn: "Dyeing Transport Cost", type: "EXPENSE", nature: "DEBIT", sectorTag: "dyeing_transport" },
            // مرحلة 4: تصنيع داخلي
            { code: "5120", nameAr: "أجور عمال القص", nameEn: "Cutting Labor", type: "EXPENSE", nature: "DEBIT", sectorTag: "labor_cutting" },
            { code: "5121", nameAr: "أجور عمال الخياطة", nameEn: "Sewing Labor", type: "EXPENSE", nature: "DEBIT", sectorTag: "labor_sewing" },
            { code: "5122", nameAr: "أجور عمال التشطيب والكي", nameEn: "Finishing Labor", type: "EXPENSE", nature: "DEBIT", sectorTag: "labor_finishing" },
            { code: "5123", nameAr: "أجور عمال التغليف", nameEn: "Packing Labor", type: "EXPENSE", nature: "DEBIT", sectorTag: "labor_packing" },
            { code: "5124", nameAr: "مواد تغليف مستخدمة", nameEn: "Packaging Materials Used", type: "EXPENSE", nature: "DEBIT", sectorTag: "packaging_used" },
          ],
        },
        {
          code: "52",
          nameAr: "تكاليف صناعية غير مباشرة",
          nameEn: "Factory Overhead",
          type: "EXPENSE",
          nature: "DEBIT",
          children: [
            { code: "5201", nameAr: "كهرباء ومياه المصنع", nameEn: "Factory Utilities", type: "EXPENSE", nature: "DEBIT", sectorTag: "factory_utilities" },
            { code: "5202", nameAr: "إيجار المصنع", nameEn: "Factory Rent", type: "EXPENSE", nature: "DEBIT", sectorTag: "factory_rent" },
            { code: "5203", nameAr: "صيانة ماكينات", nameEn: "Machine Maintenance", type: "EXPENSE", nature: "DEBIT", sectorTag: "machine_maintenance" },
            { code: "5204", nameAr: "إهلاك ماكينات ومعدات", nameEn: "Factory Depreciation", type: "EXPENSE", nature: "DEBIT", sectorTag: "factory_depreciation" },
            { code: "5205", nameAr: "تأمين المصنع", nameEn: "Factory Insurance", type: "EXPENSE", nature: "DEBIT", sectorTag: "factory_insurance" },
            { code: "5206", nameAr: "مشرفين وإدارة إنتاج", nameEn: "Production Supervision", type: "EXPENSE", nature: "DEBIT", sectorTag: "production_supervision" },
            { code: "5207", nameAr: "هالك وتالف إنتاج", nameEn: "Production Waste & Spoilage", type: "EXPENSE", nature: "DEBIT", sectorTag: "production_waste" },
          ],
        },
        {
          code: "53",
          nameAr: "المصروفات التشغيلية والإدارية",
          nameEn: "Operating & Admin Expenses",
          type: "EXPENSE",
          nature: "DEBIT",
          children: [
            { code: "5301", nameAr: "رواتب الإدارة", nameEn: "Admin Salaries", type: "EXPENSE", nature: "DEBIT", sectorTag: "admin_salaries" },
            { code: "5302", nameAr: "إيجار المكتب", nameEn: "Office Rent", type: "EXPENSE", nature: "DEBIT", sectorTag: "office_rent" },
            { code: "5303", nameAr: "كهرباء ومياه المكتب", nameEn: "Office Utilities", type: "EXPENSE", nature: "DEBIT", sectorTag: "office_utilities" },
            { code: "5304", nameAr: "مصاريف التسويق والإعلان", nameEn: "Marketing & Advertising", type: "EXPENSE", nature: "DEBIT", sectorTag: "marketing" },
            { code: "5305", nameAr: "مصاريف نقل وشحن", nameEn: "Shipping & Freight", type: "EXPENSE", nature: "DEBIT", sectorTag: "shipping" },
            { code: "5306", nameAr: "مصاريف سفر ومعارض", nameEn: "Travel & Exhibitions", type: "EXPENSE", nature: "DEBIT", sectorTag: "travel" },
            { code: "5307", nameAr: "رسوم جمركية وتخليص", nameEn: "Customs & Clearance", type: "EXPENSE", nature: "DEBIT", sectorTag: "customs" },
            { code: "5308", nameAr: "مصاريف بنكية", nameEn: "Bank Charges", type: "EXPENSE", nature: "DEBIT", sectorTag: "bank_charges" },
            { code: "5309", nameAr: "إهلاك أصول إدارية", nameEn: "Admin Depreciation", type: "EXPENSE", nature: "DEBIT", sectorTag: "admin_depreciation" },
            { code: "5310", nameAr: "تأمينات اجتماعية (حصة صاحب العمل)", nameEn: "GOSI — Employer Share", type: "EXPENSE", nature: "DEBIT", sectorTag: "gosi_employer" },
            { code: "5311", nameAr: "مصاريف متنوعة", nameEn: "Miscellaneous", type: "EXPENSE", nature: "DEBIT", sectorTag: "misc" },
          ],
        },
      ],
    },
  ],
  financialStatementMapping: {
    incomeStatement: [
      { key: "sales", nameAr: "المبيعات", nameEn: "Sales", sectorTags: ["sales_wholesale", "sales_retail", "sales_export", "sales_fabric"] },
      { key: "sales_returns", nameAr: "مردودات وخصومات", nameEn: "Returns & Discounts", sectorTags: ["sales_returns", "sales_discount"] },
      { key: "scrap", nameAr: "إيرادات هوالك", nameEn: "Scrap Revenue", sectorTags: ["scrap_revenue"] },
      { key: "direct_costs", nameAr: "تكلفة الإنتاج المباشرة", nameEn: "Direct Production Costs", accountCodes: ["51"] },
      { key: "overhead", nameAr: "تكاليف صناعية غير مباشرة", nameEn: "Factory Overhead", accountCodes: ["52"] },
      { key: "operating_expenses", nameAr: "مصروفات تشغيلية وإدارية", nameEn: "Operating & Admin Expenses", accountCodes: ["53"] },
      { key: "other_revenue", nameAr: "إيرادات أخرى", nameEn: "Other Revenue", sectorTags: ["other_revenue"] },
    ],
    balanceSheet: [
      { key: "current_assets", nameAr: "الأصول المتداولة", nameEn: "Current Assets", accountCodes: ["11"] },
      { key: "non_current_assets", nameAr: "الأصول غير المتداولة", nameEn: "Non-Current Assets", accountCodes: ["12"] },
      { key: "current_liabilities", nameAr: "الخصوم المتداولة", nameEn: "Current Liabilities", accountCodes: ["21"] },
      { key: "non_current_liabilities", nameAr: "الخصوم طويلة الأجل", nameEn: "Long-Term Liabilities", accountCodes: ["22"] },
      { key: "equity", nameAr: "حقوق الملكية", nameEn: "Equity", accountCodes: ["3"] },
    ],
  },
};
