import type { SectorConfig } from "./types";

export const industrialConfig: SectorConfig = {
  sector: "INDUSTRIAL",
  nameAr: "صناعي",
  nameEn: "Industrial (Manufacturing)",
  chartOfAccounts: [
    {
      code: "1",
      nameAr: "الأصول",
      nameEn: "Assets",
      type: "ASSET",
      nature: "DEBIT",
      isSystem: true,
      children: [
        {
          code: "11",
          nameAr: "الأصول المتداولة",
          nameEn: "Current Assets",
          type: "ASSET",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "1101", nameAr: "الصندوق", nameEn: "Cash on Hand", type: "ASSET", nature: "DEBIT", isSystem: true, sectorTag: "cash" },
            { code: "1102", nameAr: "البنك", nameEn: "Bank", type: "ASSET", nature: "DEBIT", isSystem: true, sectorTag: "bank" },
            { code: "1103", nameAr: "العملاء (المدينون)", nameEn: "Accounts Receivable", type: "ASSET", nature: "DEBIT", sectorTag: "ar" },
            { code: "1104", nameAr: "مخزون المواد الخام", nameEn: "Raw Materials Inventory", type: "ASSET", nature: "DEBIT", sectorTag: "raw_materials" },
            { code: "1105", nameAr: "إنتاج تحت التشغيل", nameEn: "Work-in-Progress Inventory", type: "ASSET", nature: "DEBIT", sectorTag: "wip" },
            { code: "1106", nameAr: "مخزون البضاعة التامة", nameEn: "Finished Goods Inventory", type: "ASSET", nature: "DEBIT", sectorTag: "finished_goods" },
            { code: "1107", nameAr: "مصروفات مدفوعة مقدمًا", nameEn: "Prepaid Expenses", type: "ASSET", nature: "DEBIT", sectorTag: "prepaid" },
            { code: "1108", nameAr: "ضريبة القيمة المضافة - مدينة", nameEn: "VAT Receivable", type: "ASSET", nature: "DEBIT", sectorTag: "vat_input" },
          ],
        },
        {
          code: "12",
          nameAr: "الأصول غير المتداولة",
          nameEn: "Non-Current Assets",
          type: "ASSET",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "1201", nameAr: "الآلات والمعدات الصناعية", nameEn: "Machinery", type: "ASSET", nature: "DEBIT", sectorTag: "ppe" },
            { code: "1202", nameAr: "المعدات", nameEn: "Equipment", type: "ASSET", nature: "DEBIT", sectorTag: "ppe" },
            { code: "1203", nameAr: "المباني", nameEn: "Buildings", type: "ASSET", nature: "DEBIT", sectorTag: "ppe" },
            { code: "1204", nameAr: "مجمع الإهلاك", nameEn: "Accumulated Depreciation", type: "ASSET", nature: "CREDIT", sectorTag: "acc_dep" },
          ],
        },
      ],
    },
    {
      code: "2",
      nameAr: "الخصوم (الالتزامات)",
      nameEn: "Liabilities",
      type: "LIABILITY",
      nature: "CREDIT",
      isSystem: true,
      children: [
        {
          code: "21",
          nameAr: "الخصوم المتداولة",
          nameEn: "Current Liabilities",
          type: "LIABILITY",
          nature: "CREDIT",
          isSystem: true,
          children: [
            { code: "2101", nameAr: "الموردون (الدائنون)", nameEn: "Accounts Payable", type: "LIABILITY", nature: "CREDIT", sectorTag: "ap" },
            { code: "2102", nameAr: "مصروفات مستحقة", nameEn: "Accrued Expenses", type: "LIABILITY", nature: "CREDIT", sectorTag: "accrued" },
            { code: "2103", nameAr: "ضريبة القيمة المضافة - دائنة", nameEn: "VAT Payable", type: "LIABILITY", nature: "CREDIT", sectorTag: "vat_output" },
            { code: "2104", nameAr: "رواتب مستحقة", nameEn: "Salaries Payable", type: "LIABILITY", nature: "CREDIT", sectorTag: "salaries_payable" },
          ],
        },
        {
          code: "22",
          nameAr: "الخصوم طويلة الأجل",
          nameEn: "Long-Term Liabilities",
          type: "LIABILITY",
          nature: "CREDIT",
          children: [
            { code: "2201", nameAr: "قروض طويلة الأجل", nameEn: "Long-Term Loans", type: "LIABILITY", nature: "CREDIT", sectorTag: "lt_loans" },
          ],
        },
      ],
    },
    {
      code: "3",
      nameAr: "حقوق الملكية",
      nameEn: "Equity",
      type: "EQUITY",
      nature: "CREDIT",
      isSystem: true,
      children: [
        { code: "3101", nameAr: "رأس المال", nameEn: "Capital", type: "EQUITY", nature: "CREDIT", isSystem: true, sectorTag: "capital" },
        { code: "3102", nameAr: "أرباح مبقاة", nameEn: "Retained Earnings", type: "EQUITY", nature: "CREDIT", isSystem: true, sectorTag: "retained_earnings" },
        { code: "3103", nameAr: "الاحتياطيات", nameEn: "Reserves", type: "EQUITY", nature: "CREDIT", sectorTag: "reserves" },
      ],
    },
    {
      code: "4",
      nameAr: "الإيرادات",
      nameEn: "Revenue",
      type: "REVENUE",
      nature: "CREDIT",
      isSystem: true,
      children: [
        { code: "4101", nameAr: "مبيعات البضاعة التامة", nameEn: "Sales of Finished Goods", type: "REVENUE", nature: "CREDIT", isSystem: true, sectorTag: "sales" },
        { code: "4102", nameAr: "مردودات المبيعات", nameEn: "Sales Returns", type: "REVENUE", nature: "DEBIT", sectorTag: "sales_returns" },
        { code: "4103", nameAr: "خصم مسموح به", nameEn: "Sales Discount", type: "REVENUE", nature: "DEBIT", sectorTag: "sales_discount" },
        { code: "4201", nameAr: "إيرادات أخرى", nameEn: "Other Revenue", type: "REVENUE", nature: "CREDIT", sectorTag: "other_revenue" },
      ],
    },
    {
      code: "5",
      nameAr: "المصروفات",
      nameEn: "Expenses",
      type: "EXPENSE",
      nature: "DEBIT",
      isSystem: true,
      children: [
        {
          code: "51",
          nameAr: "تكلفة الإنتاج",
          nameEn: "Production Costs",
          type: "EXPENSE",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "5101", nameAr: "مواد خام مستخدمة", nameEn: "Raw Materials Used", type: "EXPENSE", nature: "DEBIT", isSystem: true, sectorTag: "raw_materials_used" },
            { code: "5102", nameAr: "أجور عمالة مباشرة", nameEn: "Direct Labor", type: "EXPENSE", nature: "DEBIT", sectorTag: "direct_labor" },
            { code: "5103", nameAr: "مصاريف المصنع - كهرباء ومياه", nameEn: "Factory Utilities", type: "EXPENSE", nature: "DEBIT", sectorTag: "factory_utilities" },
            { code: "5104", nameAr: "مصاريف المصنع - صيانة", nameEn: "Factory Maintenance", type: "EXPENSE", nature: "DEBIT", sectorTag: "factory_maintenance" },
            { code: "5105", nameAr: "مصاريف المصنع - إهلاك", nameEn: "Factory Depreciation", type: "EXPENSE", nature: "DEBIT", sectorTag: "factory_depreciation" },
          ],
        },
        {
          code: "52",
          nameAr: "المصروفات التشغيلية",
          nameEn: "Operating Expenses",
          type: "EXPENSE",
          nature: "DEBIT",
          children: [
            { code: "5201", nameAr: "الرواتب والأجور", nameEn: "Salaries & Wages", type: "EXPENSE", nature: "DEBIT", sectorTag: "salaries" },
            { code: "5202", nameAr: "الإيجار", nameEn: "Rent", type: "EXPENSE", nature: "DEBIT", sectorTag: "rent" },
            { code: "5203", nameAr: "الكهرباء والمياه", nameEn: "Utilities", type: "EXPENSE", nature: "DEBIT", sectorTag: "utilities" },
            { code: "5204", nameAr: "مصاريف التسويق والإعلان", nameEn: "Marketing & Advertising", type: "EXPENSE", nature: "DEBIT" },
            { code: "5205", nameAr: "مصاريف الإهلاك - إدارية", nameEn: "Administrative Depreciation", type: "EXPENSE", nature: "DEBIT", sectorTag: "depreciation" },
            { code: "5206", nameAr: "مصاريف بنكية", nameEn: "Bank Charges", type: "EXPENSE", nature: "DEBIT" },
            { code: "5207", nameAr: "مصاريف متنوعة", nameEn: "Miscellaneous Expenses", type: "EXPENSE", nature: "DEBIT" },
          ],
        },
      ],
    },
  ],
  financialStatementMapping: {
    incomeStatement: [
      { key: "sales", nameAr: "المبيعات", nameEn: "Sales", sectorTags: ["sales"] },
      { key: "sales_returns", nameAr: "مردودات المبيعات", nameEn: "Sales Returns", sectorTags: ["sales_returns", "sales_discount"] },
      { key: "production_costs", nameAr: "تكلفة الإنتاج", nameEn: "Production Costs", accountCodes: ["51"] },
      { key: "operating_expenses", nameAr: "المصروفات التشغيلية", nameEn: "Operating Expenses", accountCodes: ["52"] },
      { key: "other_revenue", nameAr: "إيرادات أخرى", nameEn: "Other Revenue", sectorTags: ["other_revenue"] },
    ],
    balanceSheet: [
      { key: "current_assets", nameAr: "الأصول المتداولة", nameEn: "Current Assets", accountCodes: ["11"] },
      { key: "non_current_assets", nameAr: "الأصول غير المتداولة", nameEn: "Non-Current Assets", accountCodes: ["12"] },
      { key: "current_liabilities", nameAr: "الخصوم المتداولة", nameEn: "Current Liabilities", accountCodes: ["21"] },
      { key: "non_current_liabilities", nameAr: "الخصوم طويلة الأجل", nameEn: "Long-Term Liabilities", accountCodes: ["22"] },
      { key: "equity", nameAr: "حقوق الملكية", nameEn: "Equity", accountCodes: ["3"] },
    ],
  },
};
