import type { SectorConfig } from "./types";

export const insuranceConfig: SectorConfig = {
  sector: "INSURANCE",
  nameAr: "تأمين",
  nameEn: "Insurance",
  chartOfAccounts: [
    {
      code: "1",
      nameAr: "الأصول",
      nameEn: "Assets",
      type: "ASSET",
      nature: "DEBIT",
      isSystem: true,
      children: [
        {
          code: "11",
          nameAr: "الأصول المتداولة",
          nameEn: "Current Assets",
          type: "ASSET",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "1101", nameAr: "الصندوق", nameEn: "Cash on Hand", type: "ASSET", nature: "DEBIT", isSystem: true, sectorTag: "cash" },
            { code: "1102", nameAr: "البنك", nameEn: "Bank", type: "ASSET", nature: "DEBIT", isSystem: true, sectorTag: "bank" },
            { code: "1103", nameAr: "أقساط تأمين مستحقة", nameEn: "Premiums Receivable", type: "ASSET", nature: "DEBIT", sectorTag: "premiums_receivable" },
            { code: "1104", nameAr: "مستحقات إعادة التأمين", nameEn: "Reinsurance Receivable", type: "ASSET", nature: "DEBIT", sectorTag: "reinsurance_receivable" },
            { code: "1105", nameAr: "تكاليف اكتساب مؤجلة", nameEn: "Deferred Acquisition Costs", type: "ASSET", nature: "DEBIT", sectorTag: "deferred_acquisition" },
          ],
        },
        {
          code: "12",
          nameAr: "الأصول غير المتداولة",
          nameEn: "Non-Current Assets",
          type: "ASSET",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "1201", nameAr: "استثمارات مالية", nameEn: "Investments", type: "ASSET", nature: "DEBIT", sectorTag: "investments" },
            { code: "1202", nameAr: "الأصول الثابتة", nameEn: "Fixed Assets", type: "ASSET", nature: "DEBIT", sectorTag: "ppe" },
            { code: "1203", nameAr: "مجمع الإهلاك", nameEn: "Accumulated Depreciation", type: "ASSET", nature: "CREDIT", sectorTag: "acc_dep" },
          ],
        },
      ],
    },
    {
      code: "2",
      nameAr: "الخصوم (الالتزامات)",
      nameEn: "Liabilities",
      type: "LIABILITY",
      nature: "CREDIT",
      isSystem: true,
      children: [
        {
          code: "21",
          nameAr: "الخصوم الفنية",
          nameEn: "Technical Liabilities",
          type: "LIABILITY",
          nature: "CREDIT",
          isSystem: true,
          children: [
            { code: "2101", nameAr: "أقساط غير مكتسبة", nameEn: "Unearned Premiums", type: "LIABILITY", nature: "CREDIT", sectorTag: "unearned_premiums" },
            { code: "2102", nameAr: "مخصص المطالبات", nameEn: "Claims Reserves", type: "LIABILITY", nature: "CREDIT", sectorTag: "claims_reserves" },
            { code: "2103", nameAr: "مطالبات قائمة", nameEn: "Outstanding Claims", type: "LIABILITY", nature: "CREDIT", sectorTag: "outstanding_claims" },
            { code: "2104", nameAr: "مستحقات إعادة التأمين الدائنة", nameEn: "Reinsurance Payable", type: "LIABILITY", nature: "CREDIT", sectorTag: "reinsurance_payable" },
            { code: "2105", nameAr: "احتياطيات فنية", nameEn: "Technical Reserves", type: "LIABILITY", nature: "CREDIT", sectorTag: "technical_reserves" },
          ],
        },
        {
          code: "22",
          nameAr: "الخصوم الأخرى",
          nameEn: "Other Liabilities",
          type: "LIABILITY",
          nature: "CREDIT",
          children: [
            { code: "2201", nameAr: "الموردون (الدائنون)", nameEn: "Accounts Payable", type: "LIABILITY", nature: "CREDIT", sectorTag: "ap" },
            { code: "2202", nameAr: "مصروفات مستحقة", nameEn: "Accrued Expenses", type: "LIABILITY", nature: "CREDIT", sectorTag: "accrued" },
          ],
        },
      ],
    },
    {
      code: "3",
      nameAr: "حقوق الملكية",
      nameEn: "Equity",
      type: "EQUITY",
      nature: "CREDIT",
      isSystem: true,
      children: [
        { code: "3101", nameAr: "رأس المال", nameEn: "Capital", type: "EQUITY", nature: "CREDIT", isSystem: true, sectorTag: "capital" },
        { code: "3102", nameAr: "أرباح مبقاة", nameEn: "Retained Earnings", type: "EQUITY", nature: "CREDIT", isSystem: true, sectorTag: "retained_earnings" },
        { code: "3103", nameAr: "احتياطي قانوني", nameEn: "Statutory Reserves", type: "EQUITY", nature: "CREDIT", sectorTag: "statutory_reserve" },
      ],
    },
    {
      code: "4",
      nameAr: "الإيرادات",
      nameEn: "Revenue",
      type: "REVENUE",
      nature: "CREDIT",
      isSystem: true,
      children: [
        { code: "4101", nameAr: "إجمالي الأقساط المكتتبة", nameEn: "Gross Premiums Written", type: "REVENUE", nature: "CREDIT", isSystem: true, sectorTag: "gross_premiums" },
        { code: "4102", nameAr: "أقساط إعادة التأمين المتنازل عنها", nameEn: "Reinsurance Premiums Ceded", type: "REVENUE", nature: "DEBIT", sectorTag: "reinsurance_ceded" },
        { code: "4201", nameAr: "إيرادات الاستثمار", nameEn: "Investment Income", type: "REVENUE", nature: "CREDIT", sectorTag: "investment_income" },
      ],
    },
    {
      code: "5",
      nameAr: "المصروفات",
      nameEn: "Expenses",
      type: "EXPENSE",
      nature: "DEBIT",
      isSystem: true,
      children: [
        {
          code: "51",
          nameAr: "المصاريف الفنية",
          nameEn: "Technical Expenses",
          type: "EXPENSE",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "5101", nameAr: "المطالبات المتحققة", nameEn: "Claims Incurred", type: "EXPENSE", nature: "DEBIT", sectorTag: "claims_incurred" },
            { code: "5102", nameAr: "مصاريف العمولات", nameEn: "Commission Expense", type: "EXPENSE", nature: "DEBIT", sectorTag: "commission_expense" },
            { code: "5103", nameAr: "مصاريف إعادة التأمين", nameEn: "Reinsurance Expense", type: "EXPENSE", nature: "DEBIT", sectorTag: "reinsurance_expense" },
          ],
        },
        {
          code: "52",
          nameAr: "المصروفات التشغيلية",
          nameEn: "Operating Expenses",
          type: "EXPENSE",
          nature: "DEBIT",
          children: [
            { code: "5201", nameAr: "الرواتب والأجور", nameEn: "Salaries & Wages", type: "EXPENSE", nature: "DEBIT", sectorTag: "salaries" },
            { code: "5202", nameAr: "الإيجار", nameEn: "Rent", type: "EXPENSE", nature: "DEBIT", sectorTag: "rent" },
            { code: "5203", nameAr: "الكهرباء والمياه", nameEn: "Utilities", type: "EXPENSE", nature: "DEBIT", sectorTag: "utilities" },
            { code: "5204", nameAr: "مصاريف الإهلاك", nameEn: "Depreciation Expense", type: "EXPENSE", nature: "DEBIT", sectorTag: "depreciation" },
            { code: "5205", nameAr: "مصاريف متنوعة", nameEn: "Miscellaneous Expenses", type: "EXPENSE", nature: "DEBIT" },
          ],
        },
      ],
    },
  ],
  financialStatementMapping: {
    incomeStatement: [
      { key: "net_premiums", nameAr: "صافي الأقساط", nameEn: "Net Premiums", sectorTags: ["gross_premiums", "reinsurance_ceded"] },
      { key: "investment_income", nameAr: "إيرادات الاستثمار", nameEn: "Investment Income", sectorTags: ["investment_income"] },
      { key: "technical_expenses", nameAr: "المصاريف الفنية", nameEn: "Technical Expenses", accountCodes: ["51"] },
      { key: "operating_expenses", nameAr: "المصروفات التشغيلية", nameEn: "Operating Expenses", accountCodes: ["52"] },
    ],
    balanceSheet: [
      { key: "current_assets", nameAr: "الأصول المتداولة", nameEn: "Current Assets", accountCodes: ["11"] },
      { key: "non_current_assets", nameAr: "الأصول غير المتداولة", nameEn: "Non-Current Assets", accountCodes: ["12"] },
      { key: "technical_liabilities", nameAr: "الخصوم الفنية", nameEn: "Technical Liabilities", accountCodes: ["21"] },
      { key: "other_liabilities", nameAr: "الخصوم الأخرى", nameEn: "Other Liabilities", accountCodes: ["22"] },
      { key: "equity", nameAr: "حقوق الملكية", nameEn: "Equity", accountCodes: ["3"] },
    ],
  },
};
