import type { SectorConfig } from "./types";

export const medicalHospitalConfig: SectorConfig = {
  sector: "MEDICAL_HOSPITAL",
  nameAr: "مستشفيات",
  nameEn: "Medical (Hospitals)",
  chartOfAccounts: [
    {
      code: "1",
      nameAr: "الأصول",
      nameEn: "Assets",
      type: "ASSET",
      nature: "DEBIT",
      isSystem: true,
      children: [
        {
          code: "11",
          nameAr: "الأصول المتداولة",
          nameEn: "Current Assets",
          type: "ASSET",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "1101", nameAr: "الصندوق", nameEn: "Cash on Hand", type: "ASSET", nature: "DEBIT", isSystem: true, sectorTag: "cash" },
            { code: "1102", nameAr: "البنك", nameEn: "Bank", type: "ASSET", nature: "DEBIT", isSystem: true, sectorTag: "bank" },
            { code: "1103", nameAr: "ذمم المرضى المدينة", nameEn: "Patient Accounts Receivable", type: "ASSET", nature: "DEBIT", sectorTag: "patient_ar" },
            { code: "1104", nameAr: "ذمم شركات التأمين", nameEn: "Insurance Accounts Receivable", type: "ASSET", nature: "DEBIT", sectorTag: "insurance_ar" },
            { code: "1105", nameAr: "مخزون الأدوية", nameEn: "Drug Inventory", type: "ASSET", nature: "DEBIT", sectorTag: "drug_inventory" },
            { code: "1106", nameAr: "مستلزمات طبية", nameEn: "Medical Supplies", type: "ASSET", nature: "DEBIT", sectorTag: "medical_supplies" },
          ],
        },
        {
          code: "12",
          nameAr: "الأصول غير المتداولة",
          nameEn: "Non-Current Assets",
          type: "ASSET",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "1201", nameAr: "أجهزة ومعدات طبية", nameEn: "Medical Equipment", type: "ASSET", nature: "DEBIT", sectorTag: "medical_equipment" },
            { code: "1202", nameAr: "المباني", nameEn: "Buildings", type: "ASSET", nature: "DEBIT", sectorTag: "ppe" },
            { code: "1203", nameAr: "مجمع الإهلاك", nameEn: "Accumulated Depreciation", type: "ASSET", nature: "CREDIT", sectorTag: "acc_dep" },
          ],
        },
      ],
    },
    {
      code: "2",
      nameAr: "الخصوم (الالتزامات)",
      nameEn: "Liabilities",
      type: "LIABILITY",
      nature: "CREDIT",
      isSystem: true,
      children: [
        {
          code: "21",
          nameAr: "الخصوم المتداولة",
          nameEn: "Current Liabilities",
          type: "LIABILITY",
          nature: "CREDIT",
          isSystem: true,
          children: [
            { code: "2101", nameAr: "الموردون (الدائنون)", nameEn: "Accounts Payable", type: "LIABILITY", nature: "CREDIT", sectorTag: "ap" },
            { code: "2102", nameAr: "رواتب الموظفين المستحقة", nameEn: "Staff Payable", type: "LIABILITY", nature: "CREDIT", sectorTag: "staff_payable" },
            { code: "2103", nameAr: "مطالبات التأمين المستحقة", nameEn: "Insurance Claims Payable", type: "LIABILITY", nature: "CREDIT", sectorTag: "insurance_claims_payable" },
            { code: "2104", nameAr: "إيرادات مؤجلة", nameEn: "Deferred Revenue", type: "LIABILITY", nature: "CREDIT", sectorTag: "deferred_revenue" },
          ],
        },
      ],
    },
    {
      code: "3",
      nameAr: "حقوق الملكية",
      nameEn: "Equity",
      type: "EQUITY",
      nature: "CREDIT",
      isSystem: true,
      children: [
        { code: "3101", nameAr: "رأس المال", nameEn: "Capital", type: "EQUITY", nature: "CREDIT", isSystem: true, sectorTag: "capital" },
        { code: "3102", nameAr: "أرباح مبقاة", nameEn: "Retained Earnings", type: "EQUITY", nature: "CREDIT", isSystem: true, sectorTag: "retained_earnings" },
      ],
    },
    {
      code: "4",
      nameAr: "الإيرادات",
      nameEn: "Revenue",
      type: "REVENUE",
      nature: "CREDIT",
      isSystem: true,
      children: [
        { code: "4101", nameAr: "إيرادات التنويم", nameEn: "Inpatient Revenue", type: "REVENUE", nature: "CREDIT", isSystem: true, sectorTag: "inpatient_revenue" },
        { code: "4102", nameAr: "إيرادات العيادات الخارجية", nameEn: "Outpatient Revenue", type: "REVENUE", nature: "CREDIT", sectorTag: "outpatient_revenue" },
        { code: "4103", nameAr: "إيرادات الطوارئ", nameEn: "Emergency Revenue", type: "REVENUE", nature: "CREDIT", sectorTag: "emergency_revenue" },
        { code: "4104", nameAr: "إيرادات العمليات الجراحية", nameEn: "Surgery Revenue", type: "REVENUE", nature: "CREDIT", sectorTag: "surgery_revenue" },
        { code: "4105", nameAr: "إيرادات المختبر", nameEn: "Lab Revenue", type: "REVENUE", nature: "CREDIT", sectorTag: "lab_revenue" },
        { code: "4106", nameAr: "إيرادات الصيدلية", nameEn: "Pharmacy Revenue", type: "REVENUE", nature: "CREDIT", sectorTag: "pharmacy_revenue" },
      ],
    },
    {
      code: "5",
      nameAr: "المصروفات",
      nameEn: "Expenses",
      type: "EXPENSE",
      nature: "DEBIT",
      isSystem: true,
      children: [
        {
          code: "51",
          nameAr: "التكاليف الطبية المباشرة",
          nameEn: "Direct Medical Costs",
          type: "EXPENSE",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "5101", nameAr: "تكلفة المستلزمات الطبية", nameEn: "Medical Supplies Cost", type: "EXPENSE", nature: "DEBIT", sectorTag: "medical_supplies_cost" },
            { code: "5102", nameAr: "تكلفة الأدوية", nameEn: "Drug Costs", type: "EXPENSE", nature: "DEBIT", sectorTag: "drug_costs" },
            { code: "5103", nameAr: "رواتب الأطباء", nameEn: "Doctor Salaries", type: "EXPENSE", nature: "DEBIT", sectorTag: "doctor_salaries" },
            { code: "5104", nameAr: "رواتب التمريض", nameEn: "Nursing Salaries", type: "EXPENSE", nature: "DEBIT", sectorTag: "nursing_salaries" },
          ],
        },
        {
          code: "52",
          nameAr: "المصروفات التشغيلية",
          nameEn: "Operating Expenses",
          type: "EXPENSE",
          nature: "DEBIT",
          children: [
            { code: "5201", nameAr: "صيانة المعدات الطبية", nameEn: "Medical Equipment Maintenance", type: "EXPENSE", nature: "DEBIT", sectorTag: "equipment_maintenance" },
            { code: "5202", nameAr: "مصاريف الإهلاك", nameEn: "Depreciation Expense", type: "EXPENSE", nature: "DEBIT", sectorTag: "depreciation" },
            { code: "5203", nameAr: "الكهرباء والمياه", nameEn: "Utilities", type: "EXPENSE", nature: "DEBIT", sectorTag: "utilities" },
            { code: "5204", nameAr: "الرواتب الإدارية", nameEn: "Administrative Salaries", type: "EXPENSE", nature: "DEBIT", sectorTag: "salaries" },
            { code: "5205", nameAr: "الإيجار", nameEn: "Rent", type: "EXPENSE", nature: "DEBIT", sectorTag: "rent" },
            { code: "5206", nameAr: "مصاريف متنوعة", nameEn: "Miscellaneous Expenses", type: "EXPENSE", nature: "DEBIT" },
          ],
        },
      ],
    },
  ],
  financialStatementMapping: {
    incomeStatement: [
      { key: "medical_revenue", nameAr: "الإيرادات الطبية", nameEn: "Medical Revenue", sectorTags: ["inpatient_revenue", "outpatient_revenue", "emergency_revenue", "surgery_revenue", "lab_revenue", "pharmacy_revenue"] },
      { key: "direct_medical_costs", nameAr: "التكاليف الطبية المباشرة", nameEn: "Direct Medical Costs", accountCodes: ["51"] },
      { key: "operating_expenses", nameAr: "المصروفات التشغيلية", nameEn: "Operating Expenses", accountCodes: ["52"] },
    ],
    balanceSheet: [
      { key: "current_assets", nameAr: "الأصول المتداولة", nameEn: "Current Assets", accountCodes: ["11"] },
      { key: "non_current_assets", nameAr: "الأصول غير المتداولة", nameEn: "Non-Current Assets", accountCodes: ["12"] },
      { key: "current_liabilities", nameAr: "الخصوم المتداولة", nameEn: "Current Liabilities", accountCodes: ["21"] },
      { key: "equity", nameAr: "حقوق الملكية", nameEn: "Equity", accountCodes: ["3"] },
    ],
  },
};
