import type { SectorConfig } from "./types";

export const nonProfitConfig: SectorConfig = {
  sector: "NON_PROFIT",
  nameAr: "غير ربحي",
  nameEn: "Non-Profit",
  chartOfAccounts: [
    {
      code: "1",
      nameAr: "الأصول",
      nameEn: "Assets",
      type: "ASSET",
      nature: "DEBIT",
      isSystem: true,
      children: [
        {
          code: "11",
          nameAr: "الأصول المتداولة",
          nameEn: "Current Assets",
          type: "ASSET",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "1101", nameAr: "الصندوق", nameEn: "Cash on Hand", type: "ASSET", nature: "DEBIT", isSystem: true, sectorTag: "cash" },
            { code: "1102", nameAr: "البنك", nameEn: "Bank", type: "ASSET", nature: "DEBIT", isSystem: true, sectorTag: "bank" },
            { code: "1103", nameAr: "منح مستحقة القبض", nameEn: "Grants Receivable", type: "ASSET", nature: "DEBIT", sectorTag: "grants_receivable" },
            { code: "1104", nameAr: "تعهدات مستحقة القبض", nameEn: "Pledges Receivable", type: "ASSET", nature: "DEBIT", sectorTag: "pledges_receivable" },
          ],
        },
        {
          code: "12",
          nameAr: "الأصول غير المتداولة",
          nameEn: "Non-Current Assets",
          type: "ASSET",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "1201", nameAr: "المعدات", nameEn: "Equipment", type: "ASSET", nature: "DEBIT", sectorTag: "ppe" },
            { code: "1202", nameAr: "مجمع الإهلاك", nameEn: "Accumulated Depreciation", type: "ASSET", nature: "CREDIT", sectorTag: "acc_dep" },
          ],
        },
      ],
    },
    {
      code: "2",
      nameAr: "الخصوم (الالتزامات)",
      nameEn: "Liabilities",
      type: "LIABILITY",
      nature: "CREDIT",
      isSystem: true,
      children: [
        {
          code: "21",
          nameAr: "الخصوم المتداولة",
          nameEn: "Current Liabilities",
          type: "LIABILITY",
          nature: "CREDIT",
          isSystem: true,
          children: [
            { code: "2101", nameAr: "الموردون (الدائنون)", nameEn: "Accounts Payable", type: "LIABILITY", nature: "CREDIT", sectorTag: "ap" },
            { code: "2102", nameAr: "مصروفات مستحقة", nameEn: "Accrued Expenses", type: "LIABILITY", nature: "CREDIT", sectorTag: "accrued" },
            { code: "2103", nameAr: "إيرادات منح مؤجلة", nameEn: "Deferred Grant Revenue", type: "LIABILITY", nature: "CREDIT", sectorTag: "deferred_grant" },
          ],
        },
      ],
    },
    {
      code: "3",
      nameAr: "صافي الأصول",
      nameEn: "Net Assets",
      type: "EQUITY",
      nature: "CREDIT",
      isSystem: true,
      children: [
        { code: "3101", nameAr: "صافي الأصول غير المقيدة", nameEn: "Unrestricted Net Assets", type: "EQUITY", nature: "CREDIT", isSystem: true, sectorTag: "unrestricted_net_assets" },
        { code: "3102", nameAr: "صافي الأصول المقيدة مؤقتًا", nameEn: "Temporarily Restricted Net Assets", type: "EQUITY", nature: "CREDIT", isSystem: true, sectorTag: "temp_restricted" },
        { code: "3103", nameAr: "صافي الأصول المقيدة بشكل دائم", nameEn: "Permanently Restricted Net Assets", type: "EQUITY", nature: "CREDIT", isSystem: true, sectorTag: "perm_restricted" },
      ],
    },
    {
      code: "4",
      nameAr: "الإيرادات",
      nameEn: "Revenue",
      type: "REVENUE",
      nature: "CREDIT",
      isSystem: true,
      children: [
        { code: "4101", nameAr: "التبرعات", nameEn: "Donations", type: "REVENUE", nature: "CREDIT", isSystem: true, sectorTag: "donations" },
        { code: "4102", nameAr: "المنح", nameEn: "Grants", type: "REVENUE", nature: "CREDIT", sectorTag: "grants" },
        { code: "4103", nameAr: "رسوم البرامج", nameEn: "Program Fees", type: "REVENUE", nature: "CREDIT", sectorTag: "program_fees" },
        { code: "4201", nameAr: "إيرادات الاستثمار", nameEn: "Investment Income", type: "REVENUE", nature: "CREDIT", sectorTag: "investment_income" },
      ],
    },
    {
      code: "5",
      nameAr: "المصروفات",
      nameEn: "Expenses",
      type: "EXPENSE",
      nature: "DEBIT",
      isSystem: true,
      children: [
        {
          code: "51",
          nameAr: "مصروفات البرامج",
          nameEn: "Program Expenses",
          type: "EXPENSE",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "5101", nameAr: "تكاليف البرامج المباشرة", nameEn: "Direct Program Costs", type: "EXPENSE", nature: "DEBIT", sectorTag: "program_costs" },
            { code: "5102", nameAr: "رواتب موظفي البرامج", nameEn: "Program Staff Salaries", type: "EXPENSE", nature: "DEBIT", sectorTag: "program_salaries" },
            { code: "5103", nameAr: "مستلزمات البرامج", nameEn: "Program Supplies", type: "EXPENSE", nature: "DEBIT", sectorTag: "program_supplies" },
          ],
        },
        {
          code: "52",
          nameAr: "المصروفات الإدارية",
          nameEn: "Administrative Expenses",
          type: "EXPENSE",
          nature: "DEBIT",
          children: [
            { code: "5201", nameAr: "الرواتب الإدارية", nameEn: "Administrative Salaries", type: "EXPENSE", nature: "DEBIT", sectorTag: "salaries" },
            { code: "5202", nameAr: "الإيجار", nameEn: "Rent", type: "EXPENSE", nature: "DEBIT", sectorTag: "rent" },
            { code: "5203", nameAr: "الكهرباء والمياه", nameEn: "Utilities", type: "EXPENSE", nature: "DEBIT", sectorTag: "utilities" },
            { code: "5204", nameAr: "مصاريف الإهلاك", nameEn: "Depreciation Expense", type: "EXPENSE", nature: "DEBIT", sectorTag: "depreciation" },
            { code: "5205", nameAr: "مصاريف متنوعة", nameEn: "Miscellaneous Expenses", type: "EXPENSE", nature: "DEBIT" },
          ],
        },
        {
          code: "53",
          nameAr: "مصروفات جمع التبرعات",
          nameEn: "Fundraising Expenses",
          type: "EXPENSE",
          nature: "DEBIT",
          children: [
            { code: "5301", nameAr: "مصاريف حملات التبرع", nameEn: "Fundraising Campaign Costs", type: "EXPENSE", nature: "DEBIT", sectorTag: "fundraising_costs" },
            { code: "5302", nameAr: "مصاريف الفعاليات", nameEn: "Event Expenses", type: "EXPENSE", nature: "DEBIT", sectorTag: "event_expenses" },
          ],
        },
      ],
    },
  ],
  financialStatementMapping: {
    incomeStatement: [
      { key: "contributions", nameAr: "التبرعات والمنح", nameEn: "Contributions & Grants", sectorTags: ["donations", "grants"] },
      { key: "program_fees", nameAr: "رسوم البرامج", nameEn: "Program Fees", sectorTags: ["program_fees"] },
      { key: "investment_income", nameAr: "إيرادات الاستثمار", nameEn: "Investment Income", sectorTags: ["investment_income"] },
      { key: "program_expenses", nameAr: "مصروفات البرامج", nameEn: "Program Expenses", accountCodes: ["51"] },
      { key: "admin_expenses", nameAr: "المصروفات الإدارية", nameEn: "Administrative Expenses", accountCodes: ["52"] },
      { key: "fundraising_expenses", nameAr: "مصروفات جمع التبرعات", nameEn: "Fundraising Expenses", accountCodes: ["53"] },
    ],
    balanceSheet: [
      { key: "current_assets", nameAr: "الأصول المتداولة", nameEn: "Current Assets", accountCodes: ["11"] },
      { key: "non_current_assets", nameAr: "الأصول غير المتداولة", nameEn: "Non-Current Assets", accountCodes: ["12"] },
      { key: "current_liabilities", nameAr: "الخصوم المتداولة", nameEn: "Current Liabilities", accountCodes: ["21"] },
      { key: "net_assets", nameAr: "صافي الأصول", nameEn: "Net Assets", accountCodes: ["3"] },
    ],
  },
};
