import type { SectorConfig } from "./types";

export const realEstateConfig: SectorConfig = {
  sector: "REAL_ESTATE",
  nameAr: "عقاري",
  nameEn: "Real Estate",
  chartOfAccounts: [
    {
      code: "1",
      nameAr: "الأصول",
      nameEn: "Assets",
      type: "ASSET",
      nature: "DEBIT",
      isSystem: true,
      children: [
        {
          code: "11",
          nameAr: "الأصول المتداولة",
          nameEn: "Current Assets",
          type: "ASSET",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "1101", nameAr: "الصندوق", nameEn: "Cash on Hand", type: "ASSET", nature: "DEBIT", isSystem: true, sectorTag: "cash" },
            { code: "1102", nameAr: "البنك", nameEn: "Bank", type: "ASSET", nature: "DEBIT", isSystem: true, sectorTag: "bank" },
            { code: "1103", nameAr: "العملاء (المدينون)", nameEn: "Accounts Receivable", type: "ASSET", nature: "DEBIT", sectorTag: "ar" },
            { code: "1104", nameAr: "عقارات معدة للبيع", nameEn: "Properties for Sale", type: "ASSET", nature: "DEBIT", sectorTag: "properties_for_sale" },
            { code: "1105", nameAr: "عقارات تحت التطوير", nameEn: "Properties Under Development", type: "ASSET", nature: "DEBIT", sectorTag: "properties_under_dev" },
          ],
        },
        {
          code: "12",
          nameAr: "الأصول غير المتداولة",
          nameEn: "Non-Current Assets",
          type: "ASSET",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "1201", nameAr: "عقارات استثمارية", nameEn: "Investment Properties", type: "ASSET", nature: "DEBIT", sectorTag: "investment_properties" },
            { code: "1202", nameAr: "الأراضي", nameEn: "Land", type: "ASSET", nature: "DEBIT", sectorTag: "land" },
            { code: "1203", nameAr: "المباني", nameEn: "Buildings", type: "ASSET", nature: "DEBIT", sectorTag: "ppe" },
            { code: "1204", nameAr: "مجمع الإهلاك", nameEn: "Accumulated Depreciation", type: "ASSET", nature: "CREDIT", sectorTag: "acc_dep" },
          ],
        },
      ],
    },
    {
      code: "2",
      nameAr: "الخصوم (الالتزامات)",
      nameEn: "Liabilities",
      type: "LIABILITY",
      nature: "CREDIT",
      isSystem: true,
      children: [
        {
          code: "21",
          nameAr: "الخصوم المتداولة",
          nameEn: "Current Liabilities",
          type: "LIABILITY",
          nature: "CREDIT",
          isSystem: true,
          children: [
            { code: "2101", nameAr: "الموردون (الدائنون)", nameEn: "Accounts Payable", type: "LIABILITY", nature: "CREDIT", sectorTag: "ap" },
            { code: "2102", nameAr: "عربون العملاء", nameEn: "Customer Deposits", type: "LIABILITY", nature: "CREDIT", sectorTag: "customer_deposits" },
            { code: "2103", nameAr: "إيرادات مؤجلة", nameEn: "Deferred Revenue", type: "LIABILITY", nature: "CREDIT", sectorTag: "deferred_revenue" },
          ],
        },
        {
          code: "22",
          nameAr: "الخصوم طويلة الأجل",
          nameEn: "Long-Term Liabilities",
          type: "LIABILITY",
          nature: "CREDIT",
          children: [
            { code: "2201", nameAr: "قروض عقارية مستحقة", nameEn: "Mortgage Payable", type: "LIABILITY", nature: "CREDIT", sectorTag: "mortgage_payable" },
          ],
        },
      ],
    },
    {
      code: "3",
      nameAr: "حقوق الملكية",
      nameEn: "Equity",
      type: "EQUITY",
      nature: "CREDIT",
      isSystem: true,
      children: [
        { code: "3101", nameAr: "رأس المال", nameEn: "Capital", type: "EQUITY", nature: "CREDIT", isSystem: true, sectorTag: "capital" },
        { code: "3102", nameAr: "أرباح مبقاة", nameEn: "Retained Earnings", type: "EQUITY", nature: "CREDIT", isSystem: true, sectorTag: "retained_earnings" },
        { code: "3103", nameAr: "احتياطي إعادة التقييم", nameEn: "Revaluation Reserve", type: "EQUITY", nature: "CREDIT", sectorTag: "revaluation_reserve" },
      ],
    },
    {
      code: "4",
      nameAr: "الإيرادات",
      nameEn: "Revenue",
      type: "REVENUE",
      nature: "CREDIT",
      isSystem: true,
      children: [
        { code: "4101", nameAr: "إيرادات بيع العقارات", nameEn: "Property Sales Revenue", type: "REVENUE", nature: "CREDIT", isSystem: true, sectorTag: "property_sales" },
        { code: "4102", nameAr: "إيرادات الإيجار", nameEn: "Rental Income", type: "REVENUE", nature: "CREDIT", sectorTag: "rental_income" },
        { code: "4103", nameAr: "رسوم إدارة العقارات", nameEn: "Property Management Fees", type: "REVENUE", nature: "CREDIT", sectorTag: "management_fees" },
      ],
    },
    {
      code: "5",
      nameAr: "المصروفات",
      nameEn: "Expenses",
      type: "EXPENSE",
      nature: "DEBIT",
      isSystem: true,
      children: [
        {
          code: "51",
          nameAr: "تكاليف العقارات",
          nameEn: "Property Costs",
          type: "EXPENSE",
          nature: "DEBIT",
          isSystem: true,
          children: [
            { code: "5101", nameAr: "تكلفة العقارات المباعة", nameEn: "Cost of Properties Sold", type: "EXPENSE", nature: "DEBIT", sectorTag: "property_costs" },
            { code: "5102", nameAr: "مصاريف الصيانة", nameEn: "Property Maintenance", type: "EXPENSE", nature: "DEBIT", sectorTag: "property_maintenance" },
            { code: "5103", nameAr: "مصاريف إهلاك العقارات", nameEn: "Property Depreciation", type: "EXPENSE", nature: "DEBIT", sectorTag: "property_depreciation" },
          ],
        },
        {
          code: "52",
          nameAr: "المصروفات التشغيلية",
          nameEn: "Operating Expenses",
          type: "EXPENSE",
          nature: "DEBIT",
          children: [
            { code: "5201", nameAr: "الرواتب والأجور", nameEn: "Salaries & Wages", type: "EXPENSE", nature: "DEBIT", sectorTag: "salaries" },
            { code: "5202", nameAr: "الإيجار", nameEn: "Rent", type: "EXPENSE", nature: "DEBIT", sectorTag: "rent" },
            { code: "5203", nameAr: "الكهرباء والمياه", nameEn: "Utilities", type: "EXPENSE", nature: "DEBIT", sectorTag: "utilities" },
            { code: "5204", nameAr: "مصاريف التسويق والإعلان", nameEn: "Marketing & Advertising", type: "EXPENSE", nature: "DEBIT" },
            { code: "5205", nameAr: "مصاريف بنكية", nameEn: "Bank Charges", type: "EXPENSE", nature: "DEBIT" },
            { code: "5206", nameAr: "مصاريف متنوعة", nameEn: "Miscellaneous Expenses", type: "EXPENSE", nature: "DEBIT" },
          ],
        },
      ],
    },
  ],
  financialStatementMapping: {
    incomeStatement: [
      { key: "property_sales", nameAr: "إيرادات بيع العقارات", nameEn: "Property Sales", sectorTags: ["property_sales"] },
      { key: "rental_income", nameAr: "إيرادات الإيجار", nameEn: "Rental Income", sectorTags: ["rental_income", "management_fees"] },
      { key: "property_costs", nameAr: "تكاليف العقارات", nameEn: "Property Costs", accountCodes: ["51"] },
      { key: "operating_expenses", nameAr: "المصروفات التشغيلية", nameEn: "Operating Expenses", accountCodes: ["52"] },
    ],
    balanceSheet: [
      { key: "current_assets", nameAr: "الأصول المتداولة", nameEn: "Current Assets", accountCodes: ["11"] },
      { key: "non_current_assets", nameAr: "الأصول غير المتداولة", nameEn: "Non-Current Assets", accountCodes: ["12"] },
      { key: "current_liabilities", nameAr: "الخصوم المتداولة", nameEn: "Current Liabilities", accountCodes: ["21"] },
      { key: "non_current_liabilities", nameAr: "الخصوم طويلة الأجل", nameEn: "Long-Term Liabilities", accountCodes: ["22"] },
      { key: "equity", nameAr: "حقوق الملكية", nameEn: "Equity", accountCodes: ["3"] },
    ],
  },
};
